/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Sparse Jacobian Data Structures File                             */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : ifs_JacobianSP.c                          */
/* Time                 : Mon Apr 12 11:55:23 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : ifs.kpp                                   */
/* Output root filename : ifs                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifs_Parameters.h"
#include "ifs_Global.h"
#include "ifs_Sparse.h"



/* Sparse Jacobian Data                                             */

 /* Row indexes of the LU Jacobian of variables */

  int  LU_IROW[] = {
       0,  0,  0,  1,  1,  2,  2,  3,  3,  3,  3,  4,
       4,  4,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,
       7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  9,  9,
       9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
      10, 10, 11, 11, 11, 11, 11, 11, 11 }; 

 /* Column indexes of the LU Jacobian of variables */

  int  LU_ICOL[] = {
       0,  6,  7,  1,  9,  2,  3,  3,  4,  8, 10,  4,
       9, 10,  5,  6, 11,  5,  6,  7, 11,  5,  6,  7,
       8,  9, 10, 11,  6,  7,  8,  9, 10, 11,  1,  2,
       3,  4,  8,  9, 10, 11,  4,  5,  6,  7,  8,  9,
      10, 11,  5,  6,  7,  8,  9, 10, 11 }; 

 /* Compressed row indexes of the LU Jacobian of variables */

  int  LU_CROW[] = {
       0,  3,  5,  7, 11, 14, 17, 21, 28, 34, 42, 50,
      57 }; 

 /* Diagonal indexes of the LU Jacobian of variables */

  int  LU_DIAG[] = {
       0,  3,  5,  7, 11, 14, 18, 23, 30, 39, 48, 56,
      57 }; 


