/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Jacobian of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : ifs_Jacobian.c                            */
/* Time                 : Mon Apr 12 11:55:23 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : ifs.kpp                                   */
/* Output root filename : ifs                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifs_Parameters.h"
#include "ifs_Global.h"
#include "ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Jac_SP - the Jacobian of Variables in sparse matrix representation */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      JVS       - sparse Jacobian of variables                    */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Jac_SP( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double JVS[]                           /* sparse Jacobian of variables */
)
{

/* Local variables                                                  */
double B[54];                            /* Temporary array */

/* B(0) = dA(0)/dV(11)                                              */
  B[0] = RCT[0]*F[2];
/* B(2) = dA(1)/dV(9)                                               */
  B[2] = RCT[1]*V[11];
/* B(3) = dA(1)/dV(11)                                              */
  B[3] = RCT[1]*V[9];
/* B(4) = dA(2)/dV(9)                                               */
  B[4] = RCT[2]*F[2];
/* B(6) = dA(3)/dV(9)                                               */
  B[6] = RCT[3]*2*V[9];
/* B(8) = dA(5)/dV(1)                                               */
  B[8] = RCT[5]*F[2];
/* B(10) = dA(6)/dV(8)                                              */
  B[10] = RCT[6]*V[11];
/* B(11) = dA(6)/dV(11)                                             */
  B[11] = RCT[6]*V[8];
/* B(12) = dA(7)/dV(7)                                              */
  B[12] = RCT[7]*V[11];
/* B(13) = dA(7)/dV(11)                                             */
  B[13] = RCT[7]*V[7];
/* B(14) = dA(8)/dV(8)                                              */
  B[14] = RCT[8]*V[9];
/* B(15) = dA(8)/dV(9)                                              */
  B[15] = RCT[8]*V[8];
/* B(16) = dA(9)/dV(7)                                              */
  B[16] = RCT[9]*F[2];
/* B(20) = dA(11)/dV(8)                                             */
  B[20] = RCT[11]*V[10];
/* B(21) = dA(11)/dV(10)                                            */
  B[21] = RCT[11]*V[8];
/* B(22) = dA(12)/dV(9)                                             */
  B[22] = RCT[12]*V[10];
/* B(23) = dA(12)/dV(10)                                            */
  B[23] = RCT[12]*V[9];
/* B(24) = dA(13)/dV(4)                                             */
  B[24] = RCT[13]*F[2];
/* B(26) = dA(14)/dV(2)                                             */
  B[26] = RCT[14]*F[2];
/* B(28) = dA(15)/dV(3)                                             */
  B[28] = RCT[15]*F[2];
/* B(30) = dA(16)/dV(5)                                             */
  B[30] = 8e-17*V[11];
/* B(31) = dA(16)/dV(11)                                            */
  B[31] = 8e-17*V[5];
/* B(32) = dA(17)/dV(5)                                             */
  B[32] = RCT[17]*F[2];
/* B(34) = dA(18)/dV(5)                                             */
  B[34] = RCT[18]*V[6];
/* B(35) = dA(18)/dV(6)                                             */
  B[35] = RCT[18]*V[5];
/* B(36) = dA(19)/dV(11)                                            */
  B[36] = 2.7e-06;
/* B(37) = dA(20)/dV(7)                                             */
  B[37] = 0.0089;
/* B(38) = dA(21)/dV(3)                                             */
  B[38] = 2.845e-05;
/* B(39) = dA(22)/dV(3)                                             */
  B[39] = 3.734e-05;
/* B(40) = dA(23)/dV(4)                                             */
  B[40] = 5.531e-06;
/* B(41) = dA(24)/dV(6)                                             */
  B[41] = RCT[24];
/* B(42) = dA(25)/dV(6)                                             */
  B[42] = RCT[25];
/* B(43) = dA(26)/dV(1)                                             */
  B[43] = 8.881e-06;
/* B(44) = dA(27)/dV(6)                                             */
  B[44] = RCT[27];
/* B(47) = dA(30)/dV(11)                                            */
  B[47] = RCT[30];
/* B(48) = dA(31)/dV(8)                                             */
  B[48] = RCT[31];
/* B(49) = dA(32)/dV(7)                                             */
  B[49] = RCT[32];
/* B(50) = dA(33)/dV(5)                                             */
  B[50] = RCT[33];
/* B(51) = dA(34)/dV(0)                                             */
  B[51] = RCT[34];
/* B(52) = dA(35)/dV(4)                                             */
  B[52] = RCT[35];
/* B(53) = dA(36)/dV(1)                                             */
  B[53] = RCT[36];

/* Construct the Jacobian terms from B's                            */
/* JVS(0) = Jac_FULL(0,0)                                           */
  JVS[0] = -B[51];
/* JVS(1) = Jac_FULL(0,6)                                           */
  JVS[1] = 2*B[44];
/* JVS(2) = Jac_FULL(0,7)                                           */
  JVS[2] = B[16];
/* JVS(3) = Jac_FULL(1,1)                                           */
  JVS[3] = -B[8]-B[43]-B[53];
/* JVS(4) = Jac_FULL(1,9)                                           */
  JVS[4] = B[6];
/* JVS(5) = Jac_FULL(2,2)                                           */
  JVS[5] = -B[26];
/* JVS(6) = Jac_FULL(2,3)                                           */
  JVS[6] = B[28]+B[38]+B[39];
/* JVS(7) = Jac_FULL(3,3)                                           */
  JVS[7] = -B[28]-B[38]-B[39];
/* JVS(8) = Jac_FULL(3,4)                                           */
  JVS[8] = 0.4*B[24]+B[40];
/* JVS(9) = Jac_FULL(3,8)                                           */
  JVS[9] = B[20];
/* JVS(10) = Jac_FULL(3,10)                                         */
  JVS[10] = B[21];
/* JVS(11) = Jac_FULL(4,4)                                          */
  JVS[11] = -B[24]-B[40]-B[52];
/* JVS(12) = Jac_FULL(4,9)                                          */
  JVS[12] = B[22];
/* JVS(13) = Jac_FULL(4,10)                                         */
  JVS[13] = B[23];
/* JVS(14) = Jac_FULL(5,5)                                          */
  JVS[14] = -B[30]-B[32]-B[34]-B[50];
/* JVS(15) = Jac_FULL(5,6)                                          */
  JVS[15] = -B[35];
/* JVS(16) = Jac_FULL(5,11)                                         */
  JVS[16] = -B[31];
/* JVS(17) = Jac_FULL(6,5)                                          */
  JVS[17] = -B[34];
/* JVS(18) = Jac_FULL(6,6)                                          */
  JVS[18] = -B[35]-B[41]-B[42]-B[44];
/* JVS(19) = Jac_FULL(6,7)                                          */
  JVS[19] = B[12];
/* JVS(20) = Jac_FULL(6,11)                                         */
  JVS[20] = B[13];
/* JVS(21) = Jac_FULL(7,5)                                          */
  JVS[21] = B[34];
/* JVS(22) = Jac_FULL(7,6)                                          */
  JVS[22] = B[35]+B[41];
/* JVS(23) = Jac_FULL(7,7)                                          */
  JVS[23] = -B[12]-B[16]-B[37]-B[49];
/* JVS(24) = Jac_FULL(7,8)                                          */
  JVS[24] = B[10]+B[14]+B[20];
/* JVS(25) = Jac_FULL(7,9)                                          */
  JVS[25] = B[15];
/* JVS(26) = Jac_FULL(7,10)                                         */
  JVS[26] = B[21];
/* JVS(27) = Jac_FULL(7,11)                                         */
  JVS[27] = B[11]-B[13];
/* JVS(28) = Jac_FULL(8,6)                                          */
  JVS[28] = B[42];
/* JVS(29) = Jac_FULL(8,7)                                          */
  JVS[29] = B[37];
/* JVS(30) = Jac_FULL(8,8)                                          */
  JVS[30] = -B[10]-B[14]-B[20]-B[48];
/* JVS(31) = Jac_FULL(8,9)                                          */
  JVS[31] = -B[15];
/* JVS(32) = Jac_FULL(8,10)                                         */
  JVS[32] = -B[21];
/* JVS(33) = Jac_FULL(8,11)                                         */
  JVS[33] = -B[11];
/* JVS(34) = Jac_FULL(9,1)                                          */
  JVS[34] = B[8];
/* JVS(35) = Jac_FULL(9,2)                                          */
  JVS[35] = B[26];
/* JVS(36) = Jac_FULL(9,3)                                          */
  JVS[36] = B[28]+2*B[38];
/* JVS(37) = Jac_FULL(9,4)                                          */
  JVS[37] = B[40];
/* JVS(38) = Jac_FULL(9,8)                                          */
  JVS[38] = -B[14]+B[20];
/* JVS(39) = Jac_FULL(9,9)                                          */
  JVS[39] = -B[2]-B[4]-2*B[6]-B[15]-B[22];
/* JVS(40) = Jac_FULL(9,10)                                         */
  JVS[40] = B[21]-B[23];
/* JVS(41) = Jac_FULL(9,11)                                         */
  JVS[41] = B[0]-B[3];
/* JVS(42) = Jac_FULL(10,4)                                         */
  JVS[42] = 0.6*B[24];
/* JVS(43) = Jac_FULL(10,5)                                         */
  JVS[43] = 0.75*B[30]+B[32]+B[34];
/* JVS(44) = Jac_FULL(10,6)                                         */
  JVS[44] = B[35];
/* JVS(45) = Jac_FULL(10,7)                                         */
  JVS[45] = 0;
/* JVS(46) = Jac_FULL(10,8)                                         */
  JVS[46] = -B[20];
/* JVS(47) = Jac_FULL(10,9)                                         */
  JVS[47] = -B[22];
/* JVS(48) = Jac_FULL(10,10)                                        */
  JVS[48] = -B[21]-B[23];
/* JVS(49) = Jac_FULL(10,11)                                        */
  JVS[49] = 0.75*B[31];
/* JVS(50) = Jac_FULL(11,5)                                         */
  JVS[50] = -B[30];
/* JVS(51) = Jac_FULL(11,6)                                         */
  JVS[51] = B[41];
/* JVS(52) = Jac_FULL(11,7)                                         */
  JVS[52] = -B[12]+B[37];
/* JVS(53) = Jac_FULL(11,8)                                         */
  JVS[53] = -B[10];
/* JVS(54) = Jac_FULL(11,9)                                         */
  JVS[54] = -B[2];
/* JVS(55) = Jac_FULL(11,10)                                        */
  JVS[55] = 0;
/* JVS(56) = Jac_FULL(11,11)                                        */
  JVS[56] = -B[0]-B[3]-B[11]-B[13]-B[31]-B[36]-B[47];
}

/* End of Jac_SP function                                           */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      UV        - User vector for variables                       */
/*      JUV       - Jacobian times user vector                      */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Jac_SP_Vec( 
  double JVS[],                          /* sparse Jacobian of variables */
  double UV[],                           /* User vector for variables */
  double JUV[]                           /* Jacobian times user vector */
)
{
  JUV[0] = JVS[0]*UV[0]+JVS[1]*UV[6]+JVS[2]*UV[7];
  JUV[1] = JVS[3]*UV[1]+JVS[4]*UV[9];
  JUV[2] = JVS[5]*UV[2]+JVS[6]*UV[3];
  JUV[3] = JVS[7]*UV[3]+JVS[8]*UV[4]+JVS[9]*UV[8]+JVS[10]*UV[10];
  JUV[4] = JVS[11]*UV[4]+JVS[12]*UV[9]+JVS[13]*UV[10];
  JUV[5] = JVS[14]*UV[5]+JVS[15]*UV[6]+JVS[16]*UV[11];
  JUV[6] = JVS[17]*UV[5]+JVS[18]*UV[6]+JVS[19]*UV[7]+JVS[20]*UV[11];
  JUV[7] = JVS[21]*UV[5]+JVS[22]*UV[6]+JVS[23]*UV[7]+JVS[24]*UV[8]
          +JVS[25]*UV[9]+JVS[26]*UV[10]+JVS[27]*UV[11];
  JUV[8] = JVS[28]*UV[6]+JVS[29]*UV[7]+JVS[30]*UV[8]+JVS[31]*UV[9]
          +JVS[32]*UV[10]+JVS[33]*UV[11];
  JUV[9] = JVS[34]*UV[1]+JVS[35]*UV[2]+JVS[36]*UV[3]+JVS[37]*UV[4]
          +JVS[38]*UV[8]+JVS[39]*UV[9]+JVS[40]*UV[10]+JVS[41]*UV[11];
  JUV[10] = JVS[42]*UV[4]+JVS[43]*UV[5]+JVS[44]*UV[6]+JVS[46]*UV[8]
           +JVS[47]*UV[9]+JVS[48]*UV[10]+JVS[49]*UV[11];
  JUV[11] = JVS[50]*UV[5]+JVS[51]*UV[6]+JVS[52]*UV[7]+JVS[53]*UV[8]
           +JVS[54]*UV[9]+JVS[56]*UV[11];
}

/* End of Jac_SP_Vec function                                       */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector */
/*   Arguments :                                                    */
/*      JVS       - sparse Jacobian of variables                    */
/*      UV        - User vector for variables                       */
/*      JTUV      - Jacobian transposed times user vector           */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void JacTR_SP_Vec( 
  double JVS[],                          /* sparse Jacobian of variables */
  double UV[],                           /* User vector for variables */
  double JTUV[]                          /* Jacobian transposed times user vector */
)
{
  JTUV[0] = JVS[0]*UV[0];
  JTUV[1] = JVS[3]*UV[1]+JVS[34]*UV[9];
  JTUV[2] = JVS[5]*UV[2]+JVS[35]*UV[9];
  JTUV[3] = JVS[6]*UV[2]+JVS[7]*UV[3]+JVS[36]*UV[9];
  JTUV[4] = JVS[8]*UV[3]+JVS[11]*UV[4]+JVS[37]*UV[9]+JVS[42]*UV[10];
  JTUV[5] = JVS[14]*UV[5]+JVS[17]*UV[6]+JVS[21]*UV[7]+JVS[43]*UV[10]
           +JVS[50]*UV[11];
  JTUV[6] = JVS[1]*UV[0]+JVS[15]*UV[5]+JVS[18]*UV[6]+JVS[22]*UV[7]
           +JVS[28]*UV[8]+JVS[44]*UV[10]+JVS[51]*UV[11];
  JTUV[7] = JVS[2]*UV[0]+JVS[19]*UV[6]+JVS[23]*UV[7]+JVS[29]*UV[8]
           +JVS[52]*UV[11];
  JTUV[8] = JVS[9]*UV[3]+JVS[24]*UV[7]+JVS[30]*UV[8]+JVS[38]*UV[9]
           +JVS[46]*UV[10]+JVS[53]*UV[11];
  JTUV[9] = JVS[4]*UV[1]+JVS[12]*UV[4]+JVS[25]*UV[7]+JVS[31]*UV[8]
           +JVS[39]*UV[9]+JVS[47]*UV[10]+JVS[54]*UV[11];
  JTUV[10] = JVS[10]*UV[3]+JVS[13]*UV[4]+JVS[26]*UV[7]+JVS[32]*UV[8]
            +JVS[40]*UV[9]+JVS[48]*UV[10];
  JTUV[11] = JVS[16]*UV[5]+JVS[20]*UV[6]+JVS[27]*UV[7]+JVS[33]*UV[8]
            +JVS[41]*UV[9]+JVS[49]*UV[10]+JVS[56]*UV[11];
}

/* End of JacTR_SP_Vec function                                     */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


