/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* The ODE Function of Chemical Model File                          */
/*                                                                  */
/* Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  */
/*       (http://www.cs.vt.edu/~asandu/Software/KPP)                */
/* KPP is distributed under GPL, the general public licence         */
/*       (http://www.gnu.org/copyleft/gpl.html)                     */
/* (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           */
/* (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            */
/*     With important contributions from:                           */
/*        M. Damian, Villanova University, USA                      */
/*        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany */
/*                                                                  */
/* File                 : ifs_Function.c                            */
/* Time                 : Mon Apr 12 11:55:23 2021                  */
/* Working directory    : /home/WUR/krol005/kpp/examples            */
/* Equation file        : ifs.kpp                                   */
/* Output root filename : ifs                                       */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include "ifs_Parameters.h"
#include "ifs_Global.h"
#include "ifs_Sparse.h"


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
/*                                                                  */
/* Fun - time derivatives of variables - Agregate form              */
/*   Arguments :                                                    */
/*      V         - Concentrations of variable species (local)      */
/*      F         - Concentrations of fixed species (local)         */
/*      RCT       - Rate constants (local)                          */
/*      Vdot      - Time derivative of variable species concentrations */
/*                                                                  */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

void Fun( 
  double V[],                            /* Concentrations of variable species (local) */
  double F[],                            /* Concentrations of fixed species (local) */
  double RCT[],                          /* Rate constants (local) */
  double Vdot[],                         /* Time derivative of variable species concentrations */
  double A[]                             /* Time derivative of variable species concentrations */
)
{

/* Local variables                                                  */
// double A[NREACT];                        /* Rate for each equation */

/* Computation of equation rates                                    */
  A[0] = RCT[0]*V[11]*F[2];
  A[1] = RCT[1]*V[9]*V[11];
  A[2] = RCT[2]*V[9]*F[2];
  A[3] = RCT[3]*V[9]*V[9];
  A[4] = RCT[4]*F[2];
  A[5] = RCT[5]*V[1]*F[2];
  A[6] = RCT[6]*V[8]*V[11];
  A[7] = RCT[7]*V[7]*V[11];
  A[8] = RCT[8]*V[8]*V[9];
  A[9] = RCT[9]*V[7]*F[2];
  A[10] = RCT[10]*F[0]*F[2];
  A[11] = RCT[11]*V[8]*V[10];
  A[12] = RCT[12]*V[9]*V[10];
  A[13] = RCT[13]*V[4]*F[2];
  A[14] = RCT[14]*V[2]*F[2];
  A[15] = RCT[15]*V[3]*F[2];
  A[16] = 8e-17*V[5]*V[11];
  A[17] = RCT[17]*V[5]*F[2];
  A[18] = RCT[18]*V[5]*V[6];
  A[19] = 2.7e-06*V[11];
  A[20] = 0.0089*V[7];
  A[21] = 2.845e-05*V[3];
  A[22] = 3.734e-05*V[3];
  A[23] = 5.531e-06*V[4];
  A[24] = RCT[24]*V[6];
  A[25] = RCT[25]*V[6];
  A[26] = 8.881e-06*V[1];
  A[27] = RCT[27]*V[6];
  A[28] = RCT[28]*F[3];
  A[29] = RCT[29]*F[3];
  A[30] = RCT[30]*V[11];
  A[31] = RCT[31]*V[8];
  A[32] = RCT[32]*V[7];
  A[33] = RCT[33]*V[5];
  A[34] = RCT[34]*V[0];
  A[35] = RCT[35]*V[4];
  A[36] = RCT[36]*V[1];

/* Aggregate function                                               */
  Vdot[0] = A[9]+2*A[27]-A[34];
  Vdot[1] = A[3]-A[5]-A[26]-A[36];
  Vdot[2] = -A[14]+A[15]+A[21]+A[22];
  Vdot[3] = A[11]+0.4*A[13]-A[15]-A[21]-A[22]+A[23];
  Vdot[4] = A[12]-A[13]-A[23]-A[35];
  Vdot[5] = -A[16]-A[17]-A[18]+A[28]-A[33];
  Vdot[6] = A[7]-A[18]-A[24]-A[25]-A[27];
  Vdot[7] = A[6]-A[7]+A[8]-A[9]+A[11]+A[18]-A[20]+A[24]-A[32];
  Vdot[8] = -A[6]-A[8]-A[11]+A[20]+A[25]+A[29]-A[31];
  Vdot[9] = A[0]-A[1]-A[2]-2*A[3]+A[4]+A[5]-A[8]+A[11]-A[12]+A[14]
           +A[15]+2*A[21]+A[23];
  Vdot[10] = A[10]-A[11]-A[12]+0.6*A[13]+0.75*A[16]+A[17]+A[18];
  Vdot[11] = -A[0]-A[1]-A[6]-A[7]-A[16]-A[19]+A[20]+A[24]-A[30];
}

/* End of Fun function                                              */
/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */


